const SET_SELECTED_ELEMENT = "designer/SET_SELECTED_ELEMENT";
const LOAD_ELEMENTS = "designer/LOAD_ELEMENTS";
const CREATE_ELEMENT = "designer/CREATE_ELEMENT";
const REMOVE_ELEMENT = "designer/REMOVE_ELEMENT";
const UPDATE_ELEMENT = "designer/UPDATE_ELEMENT";

export { SET_SELECTED_ELEMENT, LOAD_ELEMENTS, CREATE_ELEMENT, REMOVE_ELEMENT, UPDATE_ELEMENT };
