const SET_SELECTED_ELEMENTS = "designer/SET_SELECTED_ELEMENTS";
const ADD_ELEMENTS_TO_SELECTION = "designer/ADD_ELEMENTS_TO_SELECTION";
const LOAD_ELEMENTS = "designer/LOAD_ELEMENTS";
const CREATE_ELEMENT = "designer/CREATE_ELEMENT";
const REMOVE_ELEMENT = "designer/REMOVE_ELEMENT";
const UPDATE_ELEMENT = "designer/UPDATE_ELEMENT";
const SET_CONNECTION_STATUS = "designer/SET_CONNECTION_STATUS";
const SET_EDIT_MODE = "designer/SET_EDIT_MODE";

export {
  SET_SELECTED_ELEMENTS,
  ADD_ELEMENTS_TO_SELECTION,
  LOAD_ELEMENTS,
  CREATE_ELEMENT,
  REMOVE_ELEMENT,
  UPDATE_ELEMENT,
  SET_CONNECTION_STATUS,
  SET_EDIT_MODE
};
